### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by emp3trzy** [OGTvGaming/steam-acc-generator-by-OurmineOGTv#1]
caly czas zapetla sie captcha mimo poprawnego rozwiazania.

**Comment by OGTvGaming** [comment]
Wejdź tu -> https://github.com/OGTvGaming/steam-acc-generator-by-OurmineOGTv/releases
Potem pobierz paczkę ZIP
Wypakuj ją i uruchom "Steam Account Generator.exe"

**Comment by emp3trzy** [comment]
No pobrałem tą wersję. Po przejściu weryfikacji (zielony ptaszek), naciskam OK - program ponownie prosi o rozwiązanie captchy i tak w kółko. Raz się udało, ale program się wysypał na etapie potwierdzania randomowego maila.

**Comment by OGTvGaming** [comment]
Wejdź w folder "log" który tworzy się podczas pierwszego uruchomienia, tam masz plik .txt
Otwórz ten plik .txt zaznacz wszystko (ctrl+a) skopiuj wszystko (ctrl+c) wejdź na te stronę -> https://pastebin.com/ tam w polu "New paste" wklej wszystko (ctrl+v) nic nie musisz więcej pisać ani się rejestrować, musisz tylko nacisnąć przycisk "Create New Paste"
Potem strona odeśle cię do twojej pasty, skopiuj link do tej strony gdzie będzie twój kod i wyślij mi go tutaj.

**Comment by emp3trzy** [comment]
Wypakowałem na nowo, tym razem udało się dojść do potwierdzania maila, jednak wywaliło program. Dodam też, że bardzo ciężko tą captche rozwiązać, kilkanaście prób to czasami za mało, a obrazki wolno się wczytują (po kliknięciu). W przeglądarce po 1-2 próbach przechodzi. 

https://pastebin.com/fvcijPuR

**Comment by OGTvGaming** [comment]
To są captche od google'a to że obrazki się tak wolno wczytują to wszystko jest tak zrobione przez nich.. Nie ukrywam że mnie też denerwują te captche bo zaznacze dobrze pisze że źle jest... Nie jest to wina programu.. Jeśli masz kilkanaście złotych czy tam kilka to możesz podać dane do auto-captchy i nie będziesz musiał robić ich ręcznie.. Wywaliło? Dziwne.. Jeśli to wywalanie programu będzie się zdarzać pobierz jakiegoś debugera (ja używam do tego Visual Studio 2019) 
-------------------------------------------------------------------------------------------------------------------
Aby użyć Visual Studio 2019 jako debugera musisz pobrać sam program z tej strony -> [DOWNLOAD](https://visualstudio.microsoft.com/pl/downloads/?utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=button+cta&utm_content=download+vs2019&rr=https%3A%2F%2Fdocs.microsoft.com%2Fpl-pl%2Fvisualstudio%2Fide%2Fwhats-new-visual-studio-2019%3Fview%3Dvs-2019)
Wybierasz opcję do pobrania "Za darmo" (jest to wersja dla Społeczności)
Instalujesz Visual Studio 2019.
Włączasz Visual Studio 2019, uruchamiasz program Steam Account Generator.exe
Nic w Steam Account Generator nie robisz, przechodzisz do Visual Studio 2019 
Na górnym pasku masz zieloną strzałkę skierowaną w prawo a obok tej strzałki pisze "Dołącz"
Klikasz "Dołącz" i szukasz na liście procesów "SteamAccountGenerator" zaznaczasz poprzez jedno kliknięcie LPM.
Potem klikasz dołącz, czekasz aż się dołączy, przechodzisz do Steam Account Generator.exe i robisz wszystko normalnie tworzysz sobie to konto, a w momencie jak program ci się wywali to nie wyłączasz go tylko przechodzisz do Visual Studio 2019 i wszystko co tam zobaczysz robisz screenshoty i udostępniasz je np na [imgur](https://imgur.com/) potem wysyłasz mi tutaj link.

**Comment by emp3trzy** [comment]
Ok, pozniej pobiore i spradze co tam jest nie tak. Tak czy siak dzieki za program, bardzo fajny. Na razie platnej captchy nie bede wykupowal az do czasu gdy wszystko bedzie smigac dobrze.

**Comment by OGTvGaming** [comment]
@emp3trzy Wszystko sprawdzone, narazie działa nie ma żadnych błędów tworzy konta -> https://github.com/OGTvGaming/steam-acc-generator-by-OurmineOGTv/releases i pobierasz .ZIP
